name: 'Salesforce SFDX CLI Action'
author: Felipe Echanique Torres
description: 'This action allows to use Salesforce SFDX CLI from GitHub Actions'
inputs:
  sfdx-auth-url:
    description: Authorize a Salesforce org using an SFDX auth URL
    required: false
  tarball-url:
    description: Supply a URL to a XZip'd tarball containing the version of the SFDX CLI to install. If omitted or blank, it will install the "latest" CLI
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'terminal'  
  color: 'purple'
